#!/usr/bin/env bash
# This script configures an subdomain
func(){
	Type=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4}')
	IP=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $5}')
	echo "The subdomain $2 is a $Type record and points to $IP"
}

if [ $# -eq 2 ]; then
   func $1 $2
elif [ $# -eq 1 ]; then
     func $1 www
     func $1 lb-01
     func $1 web-01
     func $1 web-02
fi
