#!/usr/bin/env bash
# This script configures an subdomain
func()
{
    SUBDOMAIN="$2"
    COMPLETE="$2.$1"
    INFO="$(dig "$COMPLETE" | grep 'ANSWER SECTION' -A1 | awk 'NR==2')"
    IP=$(echo "$INFO" | awk '{print $5}')
    RECORD=$(echo "$INFO" | awk '{print $4}')
    echo The subdomain "$SUBDOMAIN" is a "$RECORD" record and points to "$IP"
}


if [[ -z "$2" ]]
then   
    SUB_LIST="www lb-01 web-01 web-02"
    for it in $SUB_LIST; do
	func "$1" "$it"
    done
else
    func "$1" "$2"
fi

exit 0
