#!/usr/bin/env bash
# Installs the nginx engine
sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart