#!/usr/bin/env bash
# This script configures Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
change="rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _/a $change" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "/server_name _/a error_page 404 /custom_404.html; \nlocation = /custom_404.html { \n root /var/www/html; \n internal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
