#!/usr/bin/env bash
# This script configures Nginx and a redirect
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.html
change="rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _/a $change" /etc/nginx/sites-available/default
sudo service nginx restart
