#!/usr/bin/env bash
# This script creates a 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "/server_name _/a error_page 404 /custom_404.html; \nlocation = /custom_404.html { \n root /var/www/html; \n internal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
