#!/usr/bin/env bash
# This script prints the files
FILE=holbertonschool
if [[ -f "$FILE" ]] || [[ -d "$FILE" ]]
then
    echo "holbertonschool file exists"
    if [ -s "$FILE" ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ ! -d "$FILE" ]
    then
        echo "holbertonschool is a regular file"
    fi
else
echo "holbertonschool file does not exist"
fi