#!/usr/bin/env bash
# script that sets perms
Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/holberton
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
